### ISSUE TITLE
Unclear how to be part of the discussion on language evolution

### ISSUE THREAD

**Issue by Xer0Dynamite** [cplusplus/issues#3]
I've checked iocpp.org and others, but the web is not clear on how to participate in the discussion(s) on C++ (or OOP in C) evolution.  Needing to be a member seems way too restrictive for very experimental and nascent ideas like the ideas being discussed for C++23.

**Comment by jensmaurer** [comment]
C++ is an ISO standard and is developed by a committee called ISO/IEC JTC1 SC22 WG21. Please read https://isocpp.org/std for details and contact your national standardization organization if you wish to participate.
